name: CI-for-building-project-and-running-tests

on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
        # Downloads a copy of your repository on the runner.
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        # Configures the Java 11 JDK by Adoptium.
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
      # Runs the Maven package target in non-interactive mode to ensure that
      #  the code builds, tests pass, and a package can be created.
        run: mvn --batch-mode --update-snapshots verify
